development:
  clients:
    default:
      database: tech_blog_dev
      hosts:
        - localhost:27017


production:
  clients:
    default:
      database: tech_blog_prod
      hosts:
        - localhost:27017
